class DataSourceError(Exception):
    """Raised if passing an incompatible argument as data source"""
